name: Compilation Multi-Plateforme

on: [push]

jobs:
  build:
    name: Build sur ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            output_name: clean_csv_mac
            artifact_name: bin-mac
            flags: "" 
          - os: windows-latest
            output_name: clean_csv_win.exe
            artifact_name: bin-win
            # Options critiques pour inclure les DLL dans l'EXE
            flags: "-static -static-libgcc -static-libstdc++" 

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Compilation avec G++
        run: g++ -O3 main.cpp -o ${{ matrix.output_name }} ${{ matrix.flags }}

      - name: Téléverser l'exécutable temporaire
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.output_name }}

  merge:
    name: Regroupement des fichiers
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Télécharger tous les artefacts
        uses: actions/download-artifact@v4
        with:
          path: ./release
          pattern: bin-*
          merge-multiple: true

      - name: Créer le Pack Final
        uses: actions/upload-artifact@v4
        with:
          name: Pack-Nettoyeur-CSV
          path: ./release